# Generated by Django 3.2.6 on 2021-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('url_long', models.URLField()),
                ('url_short', models.CharField(blank=True, max_length=150, unique=True)),
            ],
        ),
    ]
