# Generated by Django 3.2.6 on 2021-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shortener',
            name='user_ip',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
